{
    "CVE-2023-51779": {
        "description": "\n It was discovered that a race condition existed in the Bluetooth subsystem\n of the Linux kernel, leading to a use-after-free vulnerability. A local\n attacker could use this to cause a denial of service (system crash) or\n possibly execute arbitrary code.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "MEDIUM",
        "source": "UBUNTU_CVE",
        "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-51779.html",
        "status": "ACTIVE",
        "title": "CVE-2023-51779 - linux",
        "vulnerability_id": "CVE-2023-51779",
        "vulnerable_packages": [
            {
                "arch": "AMD64",
                "epoch": 0,
                "name": "linux",
                "packageManager": "OS",
                "release": "171.189",
                "version": "5.4.0"
            }
        ]
    },
    "CVE-2023-51780": {
        "description": "\n It was discovered that a race condition existed in the ATM\n (Asynchronous Transfer Mode) subsystem of the Linux kernel, leading\n to a use-after-free vulnerability. A local attacker could use this\n to cause a denial of service (system crash) or possibly execute\n arbitrary code.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 7.0,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 7.0,
                "scoreSource": "UBUNTU_CVE",
                "scoringVector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "HIGH",
        "source": "UBUNTU_CVE",
        "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-51780.html",
        "status": "ACTIVE",
        "title": "CVE-2023-51780 - linux",
        "vulnerability_id": "CVE-2023-51780",
        "vulnerable_packages": [
            {
                "arch": "AMD64",
                "epoch": 0,
                "name": "linux",
                "packageManager": "OS",
                "release": "171.189",
                "version": "5.4.0"
            }
        ]
    },
    "CVE-2023-51781": {
        "description": "\n It was discovered that a race condition existed in the AppleTalk\n networking subsystem of the Linux kernel, leading to a use-after-free\n vulnerability. A local attacker could use this to cause a denial of\n service (system crash) or possibly execute arbitrary code.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 7.0,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 7.0,
                "scoreSource": "UBUNTU_CVE",
                "scoringVector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "HIGH",
        "source": "UBUNTU_CVE",
        "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-51781.html",
        "status": "ACTIVE",
        "title": "CVE-2023-51781 - linux",
        "vulnerability_id": "CVE-2023-51781",
        "vulnerable_packages": [
            {
                "arch": "AMD64",
                "epoch": 0,
                "name": "linux",
                "packageManager": "OS",
                "release": "171.189",
                "version": "5.4.0"
            }
        ]
    },
    "CVE-2023-51782": {
        "description": "\n It was discovered that a race condition existed in the Rose X.25\n protocol implementation in the Linux kernel, leading to a use-after-\n free vulnerability. A local attacker could use this to cause a denial\n of service (system crash) or possibly execute arbitrary code.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 7.0,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 7.0,
                "scoreSource": "UBUNTU_CVE",
                "scoringVector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "HIGH",
        "source": "UBUNTU_CVE",
        "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-51782.html",
        "status": "ACTIVE",
        "title": "CVE-2023-51782 - linux",
        "vulnerability_id": "CVE-2023-51782",
        "vulnerable_packages": [
            {
                "arch": "AMD64",
                "epoch": 0,
                "name": "linux",
                "packageManager": "OS",
                "release": "171.189",
                "version": "5.4.0"
            }
        ]
    },
    "CVE-2023-6915": {
        "description": " A Null pointer dereference problem was found in ida_free in lib/idr.c in the Linux Kernel. This issue may allow an attacker using this library to cause a denial of service problem due to a missing check at a function return.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 5.5,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 5.5,
                "scoreSource": "UBUNTU_CVE",
                "scoringVector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "version": "3.1"
            }
        },
        "severity": "MEDIUM",
        "source": "UBUNTU_CVE",
        "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-6915.html",
        "status": "ACTIVE",
        "title": "CVE-2023-6915 - linux",
        "vulnerability_id": "CVE-2023-6915",
        "vulnerable_packages": [
            {
                "arch": "AMD64",
                "epoch": 0,
                "name": "linux",
                "packageManager": "OS",
                "release": "171.189",
                "version": "5.4.0"
            }
        ]
    },
    "SNYK-PYTHON-DNSPYTHON-6241713": {
        "description": "## Overview\n\nAffected versions of this package are vulnerable to Incorrect Behavior Order in the DNS pre-processing pipeline, which allows an off-path attacker who can spoof the source IP address of a malformed DNS response packet to cause denial of service. The UDP processing functions in `query.py` and `asyncquery.py` accept the first-arriving packet before closing the receiving socket, allowing the attacker to make the remote nameserver appear unavailable for the target resolver and clients.\n## Remediation\nUpgrade `dnspython` to version 2.6.0rc1 or higher.\n## References\n- [GitHub Commit](https://github.com/rthalley/dnspython/commit/f66e25b5f549acf66d1fb6ead13eb3cff7d09af3)\n- [GitHub Issue](https://github.com/rthalley/dnspython/issues/1045)\n- [Tudoor Paper](https://lixiang521.com/publication/oakland24/sp24spring-tudoor-li.pdf)",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 5.9,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 5.9,
                "scoreSource": "SNYK",
                "scoringVector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H/E:P",
                "version": "3.1"
            }
        },
        "severity": "MEDIUM",
        "source": "SNYK",
        "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-DNSPYTHON-6241713",
        "status": "ACTIVE",
        "title": "IN1-PYTHON-DNSPYTHON-6241713 - dnspython",
        "vulnerability_id": "SNYK-PYTHON-DNSPYTHON-6241713",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/dnspython-2.5.0.dist-info/METADATA",
                "name": "dnspython",
                "packageManager": "PYTHONPKG",
                "version": "2.5.0"
            }
        ]
    },
    "SNYK-PYTHON-TRANSFORMERS-6220003": {
        "description": "## Overview\n[transformers](https://pypi.org/project/transformers) is a State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow\n\nAffected versions of this package are vulnerable to Command Injection via the `subprocess.Popen` calls. This could potentially allow for the execution of arbitrary code.\r\n\r\n\r\n**Note:**\r\nIt appears that while this issue is generally not critical for the library's primary use cases, it can become more significant in specific production environments. \r\nParticularly in scenarios where the library interacts with user-generated input, such as in web application backends, desktop applications, and cloud-based ML services, the risk of arbitrary code execution increases.\n## Remediation\nUpgrade `transformers` to version 4.37.0 or higher.\n## References\n- [Additional Information](https://bandit.readthedocs.io/en/1.7.6/plugins/b602_subprocess_popen_with_shell_equals_true.html)\n- [GitHub Commit](https://github.com/huggingface/transformers/commit/2272ab57a99bcac972b5252b87c31e24d0b25538)\n",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 6.5,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 6.5,
                "scoreSource": "SNYK",
                "scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L",
                "version": "3.1"
            }
        },
        "severity": "MEDIUM",
        "source": "SNYK",
        "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-TRANSFORMERS-6220003",
        "status": "ACTIVE",
        "title": "IN1-PYTHON-TRANSFORMERS-6220003 - transformers",
        "vulnerability_id": "SNYK-PYTHON-TRANSFORMERS-6220003",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/transformers-4.36.2.dist-info/METADATA",
                "name": "transformers",
                "packageManager": "PYTHONPKG",
                "version": "4.36.2"
            }
        ]
    }
}
