{
    "CVE-2022-40897": {
        "description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 5.9,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 5.9,
                "scoreSource": "NVD",
                "scoringVector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "version": "3.1"
            }
        },
        "severity": "MEDIUM",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
        "status": "ACTIVE",
        "title": "CVE-2022-40897 - setuptools",
        "vulnerability_id": "CVE-2022-40897",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/setuptools-59.5.0.dist-info/METADATA",
                "name": "setuptools",
                "packageManager": "PYTHONPKG",
                "version": "59.5.0"
            }
        ]
    },
    "CVE-2024-11392": {
        "description": "Hugging Face Transformers MobileViTV2 Deserialization of Untrusted Data Remote Code Execution Vulnerability. This vulnerability allows remote attackers to execute arbitrary code on affected installations of Hugging Face Transformers. User interaction is required to exploit this vulnerability in that the target must visit a malicious page or open a malicious file.\n\nThe specific flaw exists within the handling of configuration files. The issue results from the lack of proper validation of user-supplied data, which can result in deserialization of untrusted data. An attacker can leverage this vulnerability to execute code in the context of the current user. Was ZDI-CAN-24322.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 8.8,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 8.8,
                "scoreSource": "NVD",
                "scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "HIGH",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-11392",
        "status": "ACTIVE",
        "title": "CVE-2024-11392 - transformers, transformers",
        "vulnerability_id": "CVE-2024-11392",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/transformers-4.36.0.dist-info/METADATA",
                "name": "transformers",
                "packageManager": "PYTHONPKG",
                "version": "4.36.0"
            },
            {
                "epoch": 0,
                "filePath": "requirements.txt",
                "name": "transformers",
                "packageManager": "PIP",
                "version": "4.36.0"
            }
        ]
    },
    "CVE-2024-11393": {
        "description": "Hugging Face Transformers MaskFormer Model Deserialization of Untrusted Data Remote Code Execution Vulnerability. This vulnerability allows remote attackers to execute arbitrary code on affected installations of Hugging Face Transformers. User interaction is required to exploit this vulnerability in that the target must visit a malicious page or open a malicious file.\n\nThe specific flaw exists within the parsing of model files. The issue results from the lack of proper validation of user-supplied data, which can result in deserialization of untrusted data. An attacker can leverage this vulnerability to execute code in the context of the current user. Was ZDI-CAN-25191.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 8.8,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 8.8,
                "scoreSource": "NVD",
                "scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "HIGH",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-11393",
        "status": "ACTIVE",
        "title": "CVE-2024-11393 - transformers, transformers",
        "vulnerability_id": "CVE-2024-11393",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/transformers-4.36.0.dist-info/METADATA",
                "name": "transformers",
                "packageManager": "PYTHONPKG",
                "version": "4.36.0"
            },
            {
                "epoch": 0,
                "filePath": "requirements.txt",
                "name": "transformers",
                "packageManager": "PIP",
                "version": "4.36.0"
            }
        ]
    },
    "CVE-2024-11394": {
        "description": "Hugging Face Transformers Trax Model Deserialization of Untrusted Data Remote Code Execution Vulnerability. This vulnerability allows remote attackers to execute arbitrary code on affected installations of Hugging Face Transformers. User interaction is required to exploit this vulnerability in that the target must visit a malicious page or open a malicious file.\n\nThe specific flaw exists within the handling of model files. The issue results from the lack of proper validation of user-supplied data, which can result in deserialization of untrusted data. An attacker can leverage this vulnerability to execute code in the context of the current user. Was ZDI-CAN-25012.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 8.8,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 8.8,
                "scoreSource": "NVD",
                "scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "HIGH",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-11394",
        "status": "ACTIVE",
        "title": "CVE-2024-11394 - transformers, transformers",
        "vulnerability_id": "CVE-2024-11394",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/transformers-4.36.0.dist-info/METADATA",
                "name": "transformers",
                "packageManager": "PYTHONPKG",
                "version": "4.36.0"
            },
            {
                "epoch": 0,
                "filePath": "requirements.txt",
                "name": "transformers",
                "packageManager": "PIP",
                "version": "4.36.0"
            }
        ]
    },
    "CVE-2024-31580": {
        "description": "PyTorch before v2.2.0 was discovered to contain a heap buffer overflow vulnerability in the component /runtime/vararg_functions.cpp. This vulnerability allows attackers to cause a Denial of Service (DoS) via a crafted input.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-31580",
        "status": "ACTIVE",
        "title": "CVE-2024-31580 - torch",
        "vulnerability_id": "CVE-2024-31580",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/torch-2.1.2.dist-info/METADATA",
                "name": "torch",
                "packageManager": "PYTHONPKG",
                "version": "2.1.2"
            }
        ]
    },
    "CVE-2024-31583": {
        "description": "Pytorch before version v2.2.0 was discovered to contain a use-after-free vulnerability in torch/csrc/jit/mobile/interpreter.cpp.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-31583",
        "status": "ACTIVE",
        "title": "CVE-2024-31583 - torch",
        "vulnerability_id": "CVE-2024-31583",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/torch-2.1.2.dist-info/METADATA",
                "name": "torch",
                "packageManager": "PYTHONPKG",
                "version": "2.1.2"
            }
        ]
    },
    "CVE-2024-34072": {
        "description": "sagemaker-python-sdk is a library for training and deploying machine learning models on Amazon SageMaker. The sagemaker.base_deserializers.NumpyDeserializer module before v2.218.0 allows potentially unsafe deserialization when untrusted data is passed as pickled object arrays. This consequently may allow an unprivileged third party to cause remote code execution, denial of service, affecting both confidentiality and integrity. Users are advised to upgrade to version 2.218.0. Users unable to upgrade should not pass pickled numpy object arrays which originated from an untrusted source, or that could have been tampered with. Only pass pickled numpy object arrays from trusted sources.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34072",
        "status": "ACTIVE",
        "title": "CVE-2024-34072 - sagemaker",
        "vulnerability_id": "CVE-2024-34072",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/sagemaker-2.183.0.dist-info/METADATA",
                "name": "sagemaker",
                "packageManager": "PYTHONPKG",
                "version": "2.183.0"
            }
        ]
    },
    "CVE-2024-34073": {
        "description": "sagemaker-python-sdk is a library for training and deploying machine learning models on Amazon SageMaker. In affected versions the capture_dependencies function in `sagemaker.serve.save_retrive.version_1_0_0.save.utils` module allows for potentially unsafe Operating System (OS) Command Injection if inappropriate command is passed as the \u201crequirements_path\u201d parameter. This consequently may allow an unprivileged third party to cause remote code execution, denial of service, affecting both confidentiality and integrity. This issue has been addressed in version 2.214.3. Users are advised to upgrade. Users unable to upgrade should not override the \u201crequirements_path\u201d parameter of capture_dependencies function in `sagemaker.serve.save_retrive.version_1_0_0.save.utils`, and instead use the default value.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34073",
        "status": "ACTIVE",
        "title": "CVE-2024-34073 - sagemaker",
        "vulnerability_id": "CVE-2024-34073",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/sagemaker-2.183.0.dist-info/METADATA",
                "name": "sagemaker",
                "packageManager": "PYTHONPKG",
                "version": "2.183.0"
            }
        ]
    },
    "CVE-2024-3568": {
        "description": "The huggingface/transformers library is vulnerable to arbitrary code execution through deserialization of untrusted data within the `load_repo_checkpoint()` function of the `TFPreTrainedModel()` class. Attackers can execute arbitrary code and commands by crafting a malicious serialized payload, exploiting the use of `pickle.load()` on data from potentially untrusted sources. This vulnerability allows for remote code execution (RCE) by deceiving victims into loading a seemingly harmless checkpoint during a normal training process, thereby enabling attackers to execute arbitrary code on the targeted machine.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3568",
        "status": "ACTIVE",
        "title": "CVE-2024-3568 - transformers, transformers",
        "vulnerability_id": "CVE-2024-3568",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/transformers-4.36.0.dist-info/METADATA",
                "name": "transformers",
                "packageManager": "PYTHONPKG",
                "version": "4.36.0"
            },
            {
                "epoch": 0,
                "filePath": "requirements.txt",
                "name": "transformers",
                "packageManager": "PIP",
                "version": "4.36.0"
            }
        ]
    },
    "CVE-2024-5452": {
        "description": "A remote code execution (RCE) vulnerability exists in the lightning-ai/pytorch-lightning library version 2.2.1 due to improper handling of deserialized user input and mismanagement of dunder attributes by the `deepdiff` library. The library uses `deepdiff.Delta` objects to modify application state based on frontend actions. However, it is possible to bypass the intended restrictions on modifying dunder attributes, allowing an attacker to construct a serialized delta that passes the deserializer whitelist and contains dunder attributes. When processed, this can be exploited to access other modules, classes, and instances, leading to arbitrary attribute write and total RCE on any self-hosted pytorch-lightning application in its default configuration, as the delta endpoint is enabled by default.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 9.8,
        "score_details": {
            "cvss": {
                "adjustments": [],
                "score": 9.8,
                "scoreSource": "NVD",
                "scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        },
        "severity": "CRITICAL",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5452",
        "status": "ACTIVE",
        "title": "CVE-2024-5452 - pytorch-lightning, pytorch-lightning",
        "vulnerability_id": "CVE-2024-5452",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/pytorch_lightning-1.8.6.dist-info/METADATA",
                "name": "pytorch-lightning",
                "packageManager": "PYTHONPKG",
                "version": "1.8.6"
            },
            {
                "epoch": 0,
                "filePath": "requirements.txt",
                "name": "pytorch-lightning",
                "packageManager": "PIP",
                "version": "1.8.6"
            }
        ]
    },
    "CVE-2024-5980": {
        "description": "A vulnerability in the /v1/runs API endpoint of lightning-ai/pytorch-lightning v2.2.4 allows attackers to exploit path traversal when extracting tar.gz files. When the LightningApp is running with the plugin_server, attackers can deploy malicious tar.gz plugins that embed arbitrary files with path traversal vulnerabilities. This can result in arbitrary files being written to any directory in the victim's local file system, potentially leading to remote code execution.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5980",
        "status": "ACTIVE",
        "title": "CVE-2024-5980 - pytorch-lightning, pytorch-lightning",
        "vulnerability_id": "CVE-2024-5980",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/pytorch_lightning-1.8.6.dist-info/METADATA",
                "name": "pytorch-lightning",
                "packageManager": "PYTHONPKG",
                "version": "1.8.6"
            },
            {
                "epoch": 0,
                "filePath": "requirements.txt",
                "name": "pytorch-lightning",
                "packageManager": "PIP",
                "version": "1.8.6"
            }
        ]
    },
    "CVE-2024-6345": {
        "description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
        "remediation": {
            "recommendation": {
                "text": "None Provided"
            }
        },
        "score": 0.0,
        "score_details": {},
        "severity": "UNTRIAGED",
        "source": "NVD",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
        "status": "ACTIVE",
        "title": "CVE-2024-6345 - setuptools",
        "vulnerability_id": "CVE-2024-6345",
        "vulnerable_packages": [
            {
                "epoch": 0,
                "filePath": "usr/local/lib/python3.10/site-packages/setuptools-59.5.0.dist-info/METADATA",
                "name": "setuptools",
                "packageManager": "PYTHONPKG",
                "version": "59.5.0"
            }
        ]
    }
}